### ISSUE TITLE
Plan work required to satisfy the v0.1 proof-of-concept

### ISSUE THREAD

**Issue by emmaffiondavies** [AmateurPanda92/breaking-bad-mega-drive#1]
# Objective

For [v0.1](https://www.github.com/Stack-in-a-box/breaking-bad-mega-drive/milestone/1), we need to create a proof-of-concept ROM that will run successfully in a Mega Drive emulator. Content-wise, the ROM should be in a polished state as far as the opening credit screens and title screen (music included). This will be a learning exercise more than anything to determine whether I'll be able to develop a fully-fledged game.

# Work items

The items in this section will need issues making for them; tick their box once the issue's been created.

## Design

- [ ] Create a real-size mockup still of the title screen (akin to the TV show's title).
- [ ] Use VST audio plugins to arrange a MD-style version of the TV title theme.
- [ ] Develop all graphical assets needed for implementing the visuals.
- [ ] Mock-up the opening sequence animations in Adobe Animator.

## Technical

- [ ] Add a Mega Drive emulator binary to the repository for development and testing purposes.
- [ ] Establish a working build process that produces runnable Mega Drive ROMs written in C.
- [ ] Research and add a pixel artwork package to the repository.
- [ ] Research and add a Mega Drive audio tracker to the repository.
- [ ] Experiment between software-based sprite scaling or pre-rendered animated sprites for title screen.

## Implementation

- [ ] "An unofficial fangame based on AMC's 'Breaking Bad'" credits screen.
- [ ] "A Stack-in-a-box Software production" credits screen.
- [ ] "An open-source development hosted on GitHub" credits screen.
- [ ] Static image of the title screen with animated "Start game" menu selector.
- [ ] Transfer the audio tracker output to the ROM so that it plays-back through the emulator.
- [ ] Incrementally enhance the visuals of the title screen to more closely match the TV title.
- [ ] Screen to redirect people to the repo for unimplemented parts of the game.
- [ ] Input handling to skip through credit screens and to advance past title screen.

## Documentation

- [ ] Write initial repository readme (project status, roadmap, contribution guidelines, etc.).
